### PR TITLE
Shadow head/tail pointers

### PR DESCRIPTION
**Pull request by koverstreet**
I couldn't get criterion to work - I'd like to see what the new numbers are if you want to either run the benchmark or point me in the right direction with that.

### CODE REVIEW

**Comment by polyfractal** [comment]
Oh nice, thanks!  Yeah, not sure about the status of criterion these days.  I just skimmed the repo and it looks like development has resumed, but it may be in a broken state.  I'll give it a poke this weekend.

Or potentially investigate a new benchmarking library.  There's probably something available now that wasn't a year ago :)

**Comment by polyfractal** [comment]
I managed to get criterion semi-working over the weekend (panics when trying to run the "comparison" tests, but it generates the charts I care about first).  Impressive performance boost!

Master:
screen shot 2016-05-09 at 11 27 18 am

Your changes:
screen shot 2016-05-09 at 11 27 28 am

I'll merge this soon... I want to do a bit of housekeeping first (namely, trying to get criterion 100% working).  Then I'll merge, update charts and tag a new release.  

Thanks!

**Comment by polyfractal** [comment]
Bah, Criterion is turning into too much work for now, will tackle it later.  Merging, thanks!

**Comment by koverstreet** [comment]
Awesome!

**Pull request merged**
