### PR TITLE
use allocator_api.

### PR DESCRIPTION
**Pull request by chengchangwu**
I've modified the source code so it can be compiled with the newest rust nightly.

### CODE REVIEW

**Comment by polyfractal** [comment]
Oh, awesome, thanks!  I haven't been following Rust too closely lately, but this new `std::Heap` looks really convenient.  Thanks for the PR! :)

**Comment by Bobo1239** [comment]
Thanks for merging. Can you publish a new version on crates.io?

**Comment by polyfractal** [comment]
Ah sure, sorry about that. My laptop recently imploded so I've been scrambling to get things back to working order.  I'll try to do this today.

**Comment by Bobo1239** [comment]
friendly ping @polyfractal

**Comment by polyfractal** [comment]
@Bobo1239 tagged and published as `v0.2.0`.  So sorry for the delay... it's amazing how much work is needed to get back up/running after a laptop dies :(

**Comment by Bobo1239** [comment]
@polyfractal Thanks and no worries about the delay ^^

**Pull request merged**
